### ISSUE TITLE
cram files

### ISSUE THREAD

**Issue by SanVerb** [HKU-BAL/Clair3-Nova#1]
Hello

I was wondering if there are any plans in the future to support cram files as input? 

From my understanding, clair3nova does not support cram files at the moment. :)

Kind regards

Sanché Verbeeck

**Comment by SanVerb** [comment]
Hello,

My apologies!! I found out that providing .bai files with your cram files is enough to run the workflow.

However, I do get the following information in the log file:
```
.... (only last part of log file is shown) ....
INFO:root:Finish!
Total processed positions in chr15 (chunk 1/1) : 894

real	0m36.314s
user	0m42.804s
sys	0m6.069s
Traceback (most recent call last):
  File "/home/sverbeeck/DEEMPRINT/Clair3-Nova/trio/../clair3.py", line 115, in <module>
    main()
  File "/home/sverbeeck/DEEMPRINT/Clair3-Nova/trio/../clair3.py", line 102, in main
    submodule = import_module("%s.%s" % (directory, submodule_name))
  File "/home/sverbeeck/DEEMPRINT/.snakemake/conda/e7106693c564ec64c965e27eb3736d9d_/lib-python/3/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1003, in _gcd_import
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
  File "<frozen importlib._bootstrap>", line 964, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<builtin>/frozen importlib._bootstrap_external", line 687, in exec_module
  File "<builtin>/frozen importlib._bootstrap_external", line 794, in get_code
  File "<builtin>/frozen importlib._bootstrap_external", line 754, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<string>", line 249
    print("[INFO] compressing and indexing GVCF files ...")
    ^
TabError: inconsistent use of tabs and spaces in indentation
Traceback (most recent call last):
  File "/home/sverbeeck/DEEMPRINT/Clair3-Nova/trio/../clair3.py", line 115, in <module>
    main()
  File "/home/sverbeeck/DEEMPRINT/Clair3-Nova/trio/../clair3.py", line 102, in main
    submodule = import_module("%s.%s" % (directory, submodule_name))
  File "/home/sverbeeck/DEEMPRINT/.snakemake/conda/e7106693c564ec64c965e27eb3736d9d_/lib-python/3/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1003, in _gcd_import
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
  File "<frozen importlib._bootstrap>", line 964, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<builtin>/frozen importlib._bootstrap_external", line 687, in exec_module
  File "<builtin>/frozen importlib._bootstrap_external", line 794, in get_code
  File "<builtin>/frozen importlib._bootstrap_external", line 754, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<string>", line 249
    print("[INFO] compressing and indexing GVCF files ...")
    ^
TabError: inconsistent use of tabs and spaces in indentation
Traceback (most recent call last):
  File "/home/sverbeeck/DEEMPRINT/Clair3-Nova/trio/../clair3.py", line 115, in <module>
    main()
  File "/home/sverbeeck/DEEMPRINT/Clair3-Nova/trio/../clair3.py", line 102, in main
    submodule = import_module("%s.%s" % (directory, submodule_name))
  File "/home/sverbeeck/DEEMPRINT/.snakemake/conda/e7106693c564ec64c965e27eb3736d9d_/lib-python/3/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1003, in _gcd_import
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
  File "<frozen importlib._bootstrap>", line 964, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<builtin>/frozen importlib._bootstrap_external", line 687, in exec_module
  File "<builtin>/frozen importlib._bootstrap_external", line 794, in get_code
  File "<builtin>/frozen importlib._bootstrap_external", line 754, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<string>", line 249
    print("[INFO] compressing and indexing GVCF files ...")
    ^
TabError: inconsistent use of tabs and spaces in indentation

real	2m43.180s
user	4m34.766s
sys	0m37.726s
```

It seems there is a typo in file: Clair3-Nova/trio/SortVcf_Trio.py
![image](https://github.com/HKU-BAL/Clair3-Nova/assets/119843490/9043ce52-c589-428e-bb44-64218d9af6f5)

It could be that I accidently caused the typo, but I don't remember editing anything in this file so I mention it here in any case.

Kind regards

Sanché Verbeeck

**Comment by sujunhao** [comment]
Hi Sanché Verbeeck,

Thanks for your information. I confirmed that the typo is in the source [file](https://github.com/HKU-BAL/Clair3-Nova/blob/denovo/trio/SortVcf_Trio.py#L249), and I fixed it in the latest version in this repo, hope you can finally run the tool successfully.

Regards,
JH
